# Generated by Django 2.2.6 on 2019-10-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodayHolidays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_youtube',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
